# Generated by Django 3.0.7 on 2020-07-15 18:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('Title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealcarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='IndexCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('Category', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.FloatField(default=None)),
                ('mail', models.EmailField(default=None, max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('site', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('number', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('username', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('dis_price', models.FloatField(blank=True, null=True)),
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('add_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('kidB', 'Kids Boy'), ('kidG', 'Kids Girl')], default=None, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('Tops_Tshirt', 'Tops and Tshirt'), ('Hoodies_Sweatshirt', 'Hoodies and Sweatshirt'), ('Jacket_Gilets', 'Jacket and Gilet'), ('Jeans', 'Jeans'), ('Joggers', 'Joggers'), ('Shorts', 'Shorts'), ('Leathers', 'Leathers Wears'), ('BagPacks', 'BagPacks'), ('Accessories', 'Accessories'), ('Goldstar', 'Goldstar'), ('Canvas', 'Canvas'), ('Jerseys_Kits', 'Jerseys and Kits'), ('Sports', 'Sports'), ('Formals', 'Formals'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Sandal_Flipflop', 'Sandals and Flipflop'), ('Kurtha', 'Kurtha'), ('Saree', 'Saree'), ('Skirts_Pants', 'Skirts and Pants'), ('Dresses', 'Dresses'), ('Heels', 'Heels'), ('Boots', 'Boots'), ('Close_Shoe', 'CloseShoe'), ('Sandals', 'Sandals'), ('ClothingB', 'Clothing'), ('FootwearsG', 'Footwears'), ('ClothingG', 'Clothing'), ('FootwearsB', 'Footwears')], default=None, max_length=200, null=True)),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('bloglink', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('size_s', models.CharField(blank=True, max_length=5, null=True)),
                ('size_m', models.CharField(blank=True, max_length=5, null=True)),
                ('size_l', models.CharField(blank=True, max_length=5, null=True)),
                ('size_xl', models.CharField(blank=True, max_length=5, null=True)),
                ('size_xxl', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('description', models.CharField(default=None, max_length=50)),
                ('url', models.URLField(default=None)),
                ('category', models.CharField(default=None, max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.item')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('Message', models.TextField(max_length=200)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('Blog', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date', models.DateTimeField(auto_now=True)),
                ('elong', models.BooleanField(blank=True, default=False, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('item_slug', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Description', models.CharField(default=None, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
