# Generated by Django 3.0.7 on 2020-07-15 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('E_mail', models.EmailField(max_length=200)),
                ('comfirm', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Address_url', models.URLField(blank=True, null=True)),
                ('E_sewa', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Service', models.CharField(blank=True, max_length=5, null=True)),
                ('Shopkeeper', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('shop', 'Shopkeeper'), ('blog', 'Blogger')], default=None, max_length=4, null=True)),
                ('username', models.CharField(max_length=200)),
                ('Image1', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('Phone_number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('Address_url', models.URLField(blank=True, null=True)),
                ('Service', models.CharField(blank=True, max_length=5, null=True)),
                ('First_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Last_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Contact', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Address_per', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Facebook', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Instagram', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('City', models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Biratnagar', 'Biratnagar'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Nepalgunj', 'Nepalgunj')], default=None, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
